'use strict';
module.exports = {
  plan: {
    "handsOnHelp": false,
    "sessionCount": 0,
    "contactListCount": 1,
    "recruiterContactListCount": 1,
    "importDatabase": true,
    "brandLogoAndCustomColors": false,
    "contactListMemberCount": -1,
    "accountUserCount": 1,
    "exportContactListAndParticipantHistory": false,
    "exportRecruiterStats": true,
    "exportRecruiterSurveyData": false,
    "accessKlzziForum": false,
    "accessKlzziFocus": false,
    "accessKlzziSocialForum": false,
    "canInviteObserversToSession": false,
    "paidSmsCount": 0,
    "planSmsCount": 0,
    "canBuySms": false,
    "discussionGuideTips": true,
    "whiteboardDisplay": true,
    "whiteboardFunctionality": false,
    "uploadToGallery": false,
    "reportingFunctions": false,
    "pinboardDisplay": false,
    "voting": false,
    "privateMessaging": true,
    "numberOfContacts": -1,
    "availableOnTabletAndMobilePlatforms": true,
    "customEmailInvitationAndReminderMessages": true,
    "topicCount": 5,
    "priority": 1, // This is only for front end.
    "surveyCount": 1,
    "secureSsl": true,

    "monthToUseChatSessions": false,
    "unlimitedTopicChanges": false,
    "recruitNewContactList": false,
    "accessThreeChatRooms": false,
    "zapierGuestInvitationHistory": false,
  }
}
