'use strict';
module.exports = {
  plan: {
    "handsOnHelp": true,
    "monthToUseChatSessions": true,
    "topicCount": -1,
    "unlimitedTopicChanges": true,
    "numberOfContacts": -1,
    "importDatabase": true,
    "recruitNewContactList": true,
    "exportRecruiterStats": true,
    "uploadToGallery": true,
    "voting": true,
    "reportingFunctions": true,
    "privateMessaging": true,
    "availableOnTabletAndMobilePlatforms": true,
    "contactListCount": -1,
    "exportContactListAndParticipantHistory": true,
    "accountUserCount": -1,
    "brandLogoAndCustomColors": 1,
    "exportRecruiterSurveyData": true,
    "accessThreeChatRooms": false,
    "accessKlzziSocialForum": true,
    "accessKlzziForum": false,
    "accessKlzziFocus": false,
    "customEmailInvitationAndReminderMessages": false,
    "planSmsCount": 0,
    "whiteboardFunctionality": false,
    "pinboardDisplay": false,


    "priority": 2, // This is only for front end.
    "sessionCount": 1,
    "recruiterContactListCount": 1,
    "whiteboardDisplay": false,
    "discussionGuideTips": true,
    "secureSsl": true,
    "surveyCount": 1,
    "contactListMemberCount": -1,
    "canInviteObserversToSession": true,
    "paidSmsCount": 0,
    "canBuySms": true,
  },
  plan_annual: {
    "handsOnHelp": true,
    "monthToUseChatSessions": true,
    "topicCount": -1,
    "unlimitedTopicChanges": true,
    "numberOfContacts": -1,
    "importDatabase": true,
    "recruitNewContactList": true,
    "exportRecruiterStats": true,
    "uploadToGallery": true,
    "voting": true,
    "reportingFunctions": true,
    "privateMessaging": true,
    "availableOnTabletAndMobilePlatforms": true,
    "contactListCount": -1,
    "exportContactListAndParticipantHistory": true,
    "accountUserCount": -1,
    "brandLogoAndCustomColors": 1,
    "exportRecruiterSurveyData": true,
    "accessThreeChatRooms": false,
    "accessKlzziSocialForum": true,
    "accessKlzziForum": false,
    "accessKlzziFocus": false,
    "customEmailInvitationAndReminderMessages": false,
    "planSmsCount": 0,
    "whiteboardFunctionality": false,
    "pinboardDisplay": false,


    "priority": 5, // This is only for front end.
    "sessionCount": -1,
    "recruiterContactListCount": 1,
    "whiteboardDisplay": false,
    "discussionGuideTips": true,
    "secureSsl": true,
    "surveyCount": 1,
    "contactListMemberCount": -1,
    "canInviteObserversToSession": true,
    "paidSmsCount": 0,
    "canBuySms": true,
  }
};
