'use strict';
module.exports = {
  plan: {
    "handsOnHelp": true,
    "accessKlzziSocialForum": true,
    "accessKlzziForum": true,
    "accessKlzziFocus": true,
    "sessionCount": 1,
    "contactListCount": -1,
    "recruiterContactListCount": 1,
    "exportRecruiterStats": true,
    "exportRecruiterSurveyData": true,
    "exportContactListAndParticipantHistory": true,
    "numberOfContacts": -1,
    "accountUserCount": -1,
    "brandLogoAndCustomColors": 1,
    "topicCount": -1,
    "whiteboardDisplay": true,
    "uploadToGallery": true,
    "voting": true,
    "privateMessaging": true,
    "discussionGuideTips": true,
    "reportingFunctions": true,
    "availableOnTabletAndMobilePlatforms": true,
    "secureSsl": true,
    "surveyCount": 1,
    "priority": 3, // This is only for front end.
    "importDatabase": true,
    "contactListMemberCount": -1,
    "canInviteObserversToSession": true,
    "paidSmsCount": 0,
    "planSmsCount": 20,
    "canBuySms": true,
    "whiteboardFunctionality": true,
    "pinboardDisplay": true,
    "customEmailInvitationAndReminderMessages": true,
  }
};
