'use strict';
module.exports = {
  plan: {
    "sessionCount": 1,
    "contactListCount": 1,
    "recruiterContactListCount": 1,
    "importDatabase": true,
    "brandLogoAndCustomColors": true,
    "contactListMemberCount": -1,
    "accountUserCount": 1,
    "exportContactListAndParticipantHistory": false,
    "exportRecruiterStats": true,
    "exportRecruiterSurveyData": false,
    "accessKlzziForum": true,
    "accessKlzziFocus": true,
    "accessKlzziSocialForum": true,
    "canInviteObserversToSession": true,
    "paidSmsCount": 0,
    "planSmsCount": 20,
    "canBuySms": false,
    "discussionGuideTips": true,
    "whiteboardFunctionality": true,
    "whiteboardDisplay": true,
    "uploadToGallery": true,
    "reportingFunctions": true,
    "pinboardDisplay": true,
    "voting": true,
    "privateMessaging": true,
    "numberOfContacts": -1,
    "availableOnTabletAndMobilePlatforms": true,
    "customEmailInvitationAndReminderMessages": true,
    "topicCount": 10,
    "priority": -1,
    "surveyCount": 1,
    "secureSsl": true
  }
}
