'use strict';
module.exports = {
  features: [
    {name: "sessionCount", description: "Number of Chat Sessions"},
    {name: "contactListCount", description: "Number of Contact Lists"},
    {name: "recruiterContactListCount", description: "Recruiter lists (build Contact Lists on demand)"},
    {name: "importDatabase", description: "Import&Map Contacts"},
    {name: "brandLogoAndCustomColors", description: "Custom Logo & Colors"},

    //{name: "contactListMemberCount", description: "Number of Chat Sessions"},
    //{name: "accountUserCount", description: "Number of Chat Sessions"},
    {name: "exportContactListAndParticipantHistory", description: "Export Contacts"},
    {name: "exportRecruiterSurveyData", description: "Export Recruiter Data"},
    {name: "accessKlzziForum", description: "Access klzii Forum"},
    {name: "accessKlzziFocus", description: "Access klzii Focus"},
    {name: "canInviteObserversToSession", description: "Observers"},
    {name: "planSmsCount", description: "SMS Alerts (Focus)"},

    {name: "discussionGuideTips", description: "Number of Chat Sessions"},
    {name: "whiteboardFunctionality", description: "Number of Chat Sessions"},
    {name: "uploadToGallery", description: "Number of Chat Sessions"},
    {name: "reportingFunctions", description: "Number of Chat Sessions"},
    {name: "availableOnTabletAndMobilePlatforms", description: "Number of Chat Sessions"},
    {name: "customEmailInvitationAndReminderMessages", description: "Number of Chat Sessions"},
    {name: "topicCount", description: "Number of Chat Sessions"},

    {name: "priority", description: "Number of Chat Sessions"},
    {name: "surveyCount", description: "Number of Chat Sessions"},
    {name: "secureSsl", description: "Number of Chat Sessions"}
  ],
  free_trial: {
    sessionCount: 1,
    contactListCount: 1,
    recruiterContactListCount: 1,
    importDatabase: true,
    brandLogoAndCustomColors: true,
    contactListMemberCount: -1,
    accountUserCount: 1,
    exportContactListAndParticipantHistory: false,
    exportRecruiterSurveyData: false,
    accessKlzziForum: true,
    accessKlzziFocus: true,
    canInviteObserversToSession: true,
    paidSmsCount: 20,
    planSmsCount: 20,
    discussionGuideTips: true,
    whiteboardFunctionality: true,
    uploadToGallery: true,
    reportingFunctions: true,
    availableOnTabletAndMobilePlatforms: true,
    customEmailInvitationAndReminderMessages: true,
    topicCount: -1,
    priority: -1,
    surveyCount: 1,
    secureSsl: true
  },
  free_account: {
    sessionCount: 1,
    contactListCount: 1,
    recruiterContactListCount: 1,
    importDatabase: true,
    brandLogoAndCustomColors: false,
    contactListMemberCount: -1,
    accountUserCount: 1,
    exportContactListAndParticipantHistory: false,
    exportRecruiterSurveyData: false,
    accessKlzziForum: true,
    accessKlzziFocus: true,
    canInviteObserversToSession: false,
    paidSmsCount: 0,
    planSmsCount: 0,
    discussionGuideTips: true,
    whiteboardFunctionality: true,
    uploadToGallery: false,
    reportingFunctions: false,
    availableOnTabletAndMobilePlatforms: true,
    customEmailInvitationAndReminderMessages: true,
    topicCount: 5,
    priority: 1,
    surveyCount: 1,
    secureSsl: true
  },
  senior_monthly: {
    sessionCount: 8,
    contactListCount: 4,
    recruiterContactListCount: 4,
    importDatabase: true,
    brandLogoAndCustomColors: true,
    contactListMemberCount: -1,
    accountUserCount: 5,
    exportContactListAndParticipantHistory: true,
    exportRecruiterSurveyData: true,
    accessKlzziForum: true,
    accessKlzziFocus: true,
    canInviteObserversToSession: true,
    paidSmsCount: 75,
    planSmsCount: 75,
    discussionGuideTips: true,
    whiteboardFunctionality: true,
    uploadToGallery: true,
    reportingFunctions: true,
    availableOnTabletAndMobilePlatforms: true,
    customEmailInvitationAndReminderMessages: true,
    topicCount: -1,
    priority: 1,
    related: 'senior_yearly',
    surveyCount: 4,
    secureSsl: true
  },
  senior_yearly: {
    sessionCount: 8,
    contactListCount: 4,
    recruiterContactListCount: 4,
    importDatabase: true,
    brandLogoAndCustomColors: true,
    contactListMemberCount: -1,
    accountUserCount: 5,
    exportContactListAndParticipantHistory: true,
    exportRecruiterSurveyData: true,
    accessKlzziForum: true,
    accessKlzziFocus: true,
    canInviteObserversToSession: true,
    paidSmsCount: 75,
    planSmsCount: 75,
    discussionGuideTips: true,
    whiteboardFunctionality: true,
    uploadToGallery: true,
    reportingFunctions: true,
    availableOnTabletAndMobilePlatforms: true,
    customEmailInvitationAndReminderMessages: true,
    topicCount: -1,
    priority: 1,
    surveyCount: 4,
    secureSsl: true
  },
  core_monthly: {
    sessionCount: 3,
    contactListCount: 2,
    recruiterContactListCount: 2,
    importDatabase: true,
    brandLogoAndCustomColors: true,
    contactListMemberCount: -1,
    accountUserCount: 2,
    exportContactListAndParticipantHistory: true,
    exportRecruiterSurveyData: true,
    accessKlzziForum: true,
    accessKlzziFocus: true,
    canInviteObserversToSession: true,
    paidSmsCount: 50,
    planSmsCount: 50,
    discussionGuideTips: true,
    whiteboardFunctionality: true,
    uploadToGallery: true,
    reportingFunctions: true,
    availableOnTabletAndMobilePlatforms: true,
    customEmailInvitationAndReminderMessages: true,
    topicCount: 20,
    priority: 2,
    related: 'core_yearly',
    surveyCount: 2,
    secureSsl: true
  },
  core_yearly: {
    sessionCount: 3,
    contactListCount: 2,
    recruiterContactListCount: 2,
    importDatabase: true,
    brandLogoAndCustomColors: true,
    contactListMemberCount: -1,
    accountUserCount: 2,
    exportContactListAndParticipantHistory: true,
    exportRecruiterSurveyData: true,
    accessKlzziForum: true,
    accessKlzziFocus: true,
    canInviteObserversToSession: true,
    paidSmsCount: 50,
    planSmsCount: 50,
    discussionGuideTips: true,
    whiteboardFunctionality: true,
    uploadToGallery: true,
    reportingFunctions: true,
    availableOnTabletAndMobilePlatforms: true,
    customEmailInvitationAndReminderMessages: true,
    topicCount: 20,
    priority: 2,
    surveyCount: 2,
    secureSsl: true
  },
  junior_monthly: {
    sessionCount: 1,
    contactListCount: 1,
    recruiterContactListCount: 1,
    importDatabase: true,
    brandLogoAndCustomColors: false,
    contactListMemberCount: -1,
    accountUserCount: 1,
    exportContactListAndParticipantHistory: false,
    exportRecruiterSurveyData: false,
    accessKlzziForum: true,
    accessKlzziFocus: true,
    canInviteObserversToSession: false,
    paidSmsCount: 20,
    planSmsCount: 20,
    discussionGuideTips: true,
    whiteboardFunctionality: true,
    uploadToGallery: true,
    reportingFunctions: true,
    availableOnTabletAndMobilePlatforms: true,
    customEmailInvitationAndReminderMessages: true,
    topicCount: 5,
    priority: 3,
    related: 'junior_yearly',
    surveyCount: 1,
    secureSsl: true
  },
  junior_yearly: {
    sessionCount: 1,
    contactListCount: 1,
    recruiterContactListCount: 1,
    importDatabase: true,
    brandLogoAndCustomColors: false,
    contactListMemberCount: -1,
    accountUserCount: 1,
    exportContactListAndParticipantHistory: false,
    exportRecruiterSurveyData: false,
    accessKlzziForum: true,
    accessKlzziFocus: true,
    canInviteObserversToSession: false,
    paidSmsCount: 20,
    planSmsCount: 20,
    discussionGuideTips: true,
    whiteboardFunctionality: true,
    uploadToGallery: true,
    reportingFunctions: true,
    availableOnTabletAndMobilePlatforms: true,
    customEmailInvitationAndReminderMessages: true,
    topicCount: 5,
    priority: 3,
    surveyCount: 1,
    secureSsl: true
  }
}
