'use strict';
module.exports = {
  features: [
    {key: "accessKlzziForum", type: "Boolean", title: "Access klzii Forum"},
    {key: "accessKlzziFocus", type: "Boolean", title: "Access klzii Focus"},
    {key: "sessionCount", type: "Number", title: "Number of Chat Sessions"},
    {key: "contactListCount", type: "Number", title: "Number of Contact Lists"},
    {key: "recruiterContactListCount", type: "Number", title: "# of Recruiter/Social Surveys"},
    {key: "exportRecruiterStats", type: "Boolean", title: "Export Recruiter Stats"},
    {key: "exportRecruiterSurveyData", type: "Boolean", title: "Export Recruiter Data"},
    {key: "importDatabase", type: "Boolean", title: "Import & Map Contacts"},
    {key: "exportContactListAndParticipantHistory", type: "Boolean", title: "Export Contacts"},
    {key: "numberOfContacts", type: "Number", title: "Number of Contacts"},
    {key: "accountUserCount", type: "Number", title: "Number of Managers"},
    {key: "brandLogoAndCustomColors", type: "Boolean", title: "Custom Logo and Colors"},
    {key: "customEmailInvitationAndReminderMessages", type: "Boolean", title: "Custom Emails"},
    {key: "planSmsCount", type: "Number", title: "SMS Alerts (Focus)"},
    {key: "topicCount", type: "Number", title: "Number of Topics"},
    {key: "canInviteObserversToSession", type: "Boolean", title: "Spectators"},
    {key: "whiteboardDisplay", type: "Boolean", title: "Whiteboard-Display"},
    {key: "whiteboardFunctionality", type: "Boolean", title: "Whiteboard-Interactive"},
    {key: "pinboardDisplay", type: "Boolean", title: "Pinboard"},
    {key: "uploadToGallery", type: "Boolean", title: "Multimedia"},
    {key: "voting", type: "Boolean", title: "Voting"},
    {key: "privateMessaging", type: "Boolean", title: "Private Messaging"},
    {key: "discussionGuideTips", type: "Boolean", title: "Host Tips"},
    {key: "reportingFunctions", type: "Boolean", title: "Export Reporting"},
    {key: "availableOnTabletAndMobilePlatforms", type: "Boolean", title: "Mobile & Tablet"},
    {key: "secureSsl", type: "Boolean", title: "Private & Secure (SSL)"},
  ],
  free_trial: {
    sessionCount: 1,
    contactListCount: 1,
    recruiterContactListCount: 1,
    importDatabase: true,
    brandLogoAndCustomColors: true,
    contactListMemberCount: -1,
    accountUserCount: 1,
    exportContactListAndParticipantHistory: false,
    exportRecruiterStats: true,
    exportRecruiterSurveyData: false,
    accessKlzziForum: true,
    accessKlzziFocus: true,
    canInviteObserversToSession: true,
    paidSmsCount: 20,
    planSmsCount: 20,
    discussionGuideTips: true,
    whiteboardFunctionality: true,
    whiteboardDisplay: false,
    uploadToGallery: true,
    reportingFunctions: true,
    pinboardDisplay: true,
    voting: true,
    privateMessaging: true,
    numberOfContacts: -1,
    availableOnTabletAndMobilePlatforms: true,
    customEmailInvitationAndReminderMessages: true,
    topicCount: -1,
    priority: -1,
    surveyCount: 1,
    secureSsl: true
  },
  free_account: {
    sessionCount: 1,
    contactListCount: 1,
    recruiterContactListCount: 1,
    importDatabase: true,
    brandLogoAndCustomColors: false,
    contactListMemberCount: -1,
    accountUserCount: 1,
    exportContactListAndParticipantHistory: false,
    exportRecruiterStats: true,
    exportRecruiterSurveyData: false,
    accessKlzziForum: true,
    accessKlzziFocus: true,
    canInviteObserversToSession: false,
    paidSmsCount: 0,
    planSmsCount: 0,
    discussionGuideTips: true,
    whiteboardDisplay: true,
    whiteboardFunctionality: false,
    uploadToGallery: false,
    reportingFunctions: false,
    pinboardDisplay: false,
    voting: false,
    privateMessaging: true,
    numberOfContacts: -1,
    availableOnTabletAndMobilePlatforms: true,
    customEmailInvitationAndReminderMessages: true,
    topicCount: 5,
    priority: 1,
    surveyCount: 1,
    secureSsl: true
  },
  senior_monthly: {
    sessionCount: 8,
    contactListCount: 4,
    recruiterContactListCount: 4,
    importDatabase: true,
    brandLogoAndCustomColors: true,
    contactListMemberCount: -1,
    accountUserCount: 5,
    exportContactListAndParticipantHistory: true,
    exportRecruiterStats: true,
    exportRecruiterSurveyData: true,
    accessKlzziForum: true,
    accessKlzziFocus: true,
    canInviteObserversToSession: true,
    paidSmsCount: 75,
    planSmsCount: 75,
    discussionGuideTips: true,
    whiteboardDisplay: true,
    whiteboardFunctionality: true,
    uploadToGallery: true,
    reportingFunctions: true,
    pinboardDisplay: true,
    voting: true,
    privateMessaging: true,
    numberOfContacts: -1,
    availableOnTabletAndMobilePlatforms: true,
    customEmailInvitationAndReminderMessages: true,
    topicCount: -1,
    priority: 2,
    related: 'senior_yearly',
    surveyCount: 4,
    secureSsl: true
  },
  senior_yearly: {
    sessionCount: 8,
    contactListCount: 4,
    recruiterContactListCount: 4,
    importDatabase: true,
    brandLogoAndCustomColors: true,
    contactListMemberCount: -1,
    accountUserCount: 5,
    exportContactListAndParticipantHistory: true,
    exportRecruiterStats: true,
    exportRecruiterSurveyData: true,
    accessKlzziForum: true,
    accessKlzziFocus: true,
    canInviteObserversToSession: true,
    paidSmsCount: 75,
    planSmsCount: 75,
    discussionGuideTips: true,
    whiteboardDisplay: true,
    whiteboardFunctionality: true,
    uploadToGallery: true,
    reportingFunctions: true,
    pinboardDisplay: true,
    voting: true,
    privateMessaging: true,
    numberOfContacts: -1,
    availableOnTabletAndMobilePlatforms: true,
    customEmailInvitationAndReminderMessages: true,
    topicCount: -1,
    priority: 2,
    surveyCount: 4,
    secureSsl: true
  },
  core_monthly: {
    sessionCount: 3,
    contactListCount: 2,
    recruiterContactListCount: 2,
    importDatabase: true,
    brandLogoAndCustomColors: true,
    contactListMemberCount: -1,
    accountUserCount: 2,
    exportContactListAndParticipantHistory: true,
    exportRecruiterStats: true,
    exportRecruiterSurveyData: true,
    accessKlzziForum: true,
    accessKlzziFocus: true,
    canInviteObserversToSession: true,
    paidSmsCount: 50,
    planSmsCount: 50,
    discussionGuideTips: true,
    whiteboardDisplay: true,
    whiteboardFunctionality: true,
    uploadToGallery: true,
    reportingFunctions: true,
    pinboardDisplay: true,
    voting: true,
    privateMessaging: true,
    numberOfContacts: -1,
    availableOnTabletAndMobilePlatforms: true,
    customEmailInvitationAndReminderMessages: true,
    topicCount: 20,
    priority: 3,
    related: 'core_yearly',
    surveyCount: 2,
    secureSsl: true
  },
  core_yearly: {
    sessionCount: 3,
    contactListCount: 2,
    recruiterContactListCount: 2,
    importDatabase: true,
    brandLogoAndCustomColors: true,
    contactListMemberCount: -1,
    accountUserCount: 2,
    exportContactListAndParticipantHistory: true,
    exportRecruiterStats: true,
    exportRecruiterSurveyData: true,
    accessKlzziForum: true,
    accessKlzziFocus: true,
    canInviteObserversToSession: true,
    paidSmsCount: 50,
    planSmsCount: 50,
    discussionGuideTips: true,
    whiteboardDisplay: true,
    whiteboardFunctionality: true,
    uploadToGallery: true,
    reportingFunctions: true,
    pinboardDisplay: true,
    voting: true,
    privateMessaging: true,
    availableOnTabletAndMobilePlatforms: true,
    customEmailInvitationAndReminderMessages: true,
    topicCount: 20,
    priority: 3,
    surveyCount: 2,
    secureSsl: true
  },
  junior_monthly: {
    sessionCount: 1,
    contactListCount: 1,
    recruiterContactListCount: 1,
    importDatabase: true,
    brandLogoAndCustomColors: false,
    contactListMemberCount: -1,
    accountUserCount: 1,
    exportContactListAndParticipantHistory: false,
    exportRecruiterStats: true,
    exportRecruiterSurveyData: false,
    accessKlzziForum: true,
    accessKlzziFocus: true,
    canInviteObserversToSession: false,
    paidSmsCount: 20,
    planSmsCount: 20,
    discussionGuideTips: true,
    whiteboardDisplay: true,
    whiteboardFunctionality: false,
    uploadToGallery: true,
    reportingFunctions: true,
    pinboardDisplay: false,
    voting: true,
    privateMessaging: true,
    numberOfContacts: -1,
    availableOnTabletAndMobilePlatforms: true,
    customEmailInvitationAndReminderMessages: true,
    topicCount: 5,
    priority: 4,
    related: 'junior_yearly',
    surveyCount: 1,
    secureSsl: true
  },
  junior_yearly: {
    sessionCount: 1,
    contactListCount: 1,
    recruiterContactListCount: 1,
    importDatabase: true,
    brandLogoAndCustomColors: false,
    contactListMemberCount: -1,
    accountUserCount: 1,
    exportContactListAndParticipantHistory: false,
    exportRecruiterStats: true,
    exportRecruiterSurveyData: false,
    accessKlzziForum: true,
    accessKlzziFocus: true,
    canInviteObserversToSession: false,
    paidSmsCount: 20,
    planSmsCount: 20,
    discussionGuideTips: true,
    whiteboardDisplay: true,
    whiteboardFunctionality: false,
    uploadToGallery: true,
    reportingFunctions: true,
    pinboardDisplay: false,
    voting: false,
    privateMessaging: true,
    numberOfContacts: -1,
    availableOnTabletAndMobilePlatforms: true,
    customEmailInvitationAndReminderMessages: true,
    topicCount: 5,
    priority: 4,
    surveyCount: 1,
    secureSsl: true
  }
}
