'use strict';
module.exports = {
  // reorder features based on checkout page
  features: [
    { key: "handsOnHelp",                               type: "Boolean",     title: "Hands-On Help"                   },
    { key: "monthToUseChatSessions",                    type: "Boolean",     title: "Month to use Chat Sessions"      },
    { key: "topicCount",                                type: "Number",      title: " Topics"                     },
    { key: "unlimitedTopicChanges",                     type: "Boolean",     title: "Unlimited Topic Changes"      },
    { key: "numberOfContacts",                          type: "Number",      title: " Contacts"                   },
    { key: "importDatabase",                            type: "Boolean",     title: "Import a Contact List or"             },
    { key: "recruitNewContactList",                     type: "Boolean",     title: "Recruit a new Contact List"             },
    { key: "exportRecruiterStats",                      type: "Boolean",     title: "Export Recruiter Stats"   },
    { key: "uploadToGallery",                           type: "Boolean",     title: "Multimedia"                      },
    { key: "voting",                                    type: "Boolean",     title: "Voting"                          },
    { key: "reportingFunctions",                        type: "Boolean",     title: "Export Reporting"                },
    { key: "privateMessaging",                          type: "Boolean",     title: "Private Messaging"               },
    { key: "availableOnTabletAndMobilePlatforms",       type: "Boolean",     title: "Mobile&Tablet"                   },
    { key: "contactListCount",                          type: "Number",      title: " Contact Lists"              },
    { key: "exportContactListAndParticipantHistory",    type: "Boolean",     title: "Export Contacts"                 },
    { key: "accountUserCount",                          type: "Number",      title: " Account Mgrs"                   },
    { key: "brandLogoAndCustomColors",                  type: "Number",      title: "Customize Logo & Colors"              },
    { key: "exportRecruiterSurveyData",                 type: "Boolean",     title: "Export Survey Recruiter Data"    },
    { key: "accessThreeChatRooms",                      type: "Boolean",     title: "Access 3 Chat Rooms"             },
    { key: "accessKlzziSocialForum",                    type: "Boolean",     title: "Social Forum"             },
    { key: "accessKlzziForum",                          type: "Boolean",     title: "Forum Chat"              },
    { key: "accessKlzziFocus",                          type: "Boolean",     title: "Focus Chat"              },
    { key: "customEmailInvitationAndReminderMessages",  type: "Boolean",     title: "Custom Emails"                   },
    { key: "planSmsCount",                              type: "NumberLimit", title: "SMS Alerts"              },
    { key: "whiteboardFunctionality",                   type: "Boolean",     title: "Interactive Whiteboard"          },
    { key: "pinboardDisplay",                           type: "Boolean",     title: "Pinboard"                        },
    { key: "zapierGuestInvitationHistory",              type: "Boolean",     title: "Zapier Guest Invitation History" },

    // { key: "sessionCount",                              type: "Number",      title: " Chat Sessions"              },
    // { key: "recruiterContactListCount",                 type: "Number",      title: " Recruiter Social/Surveys"   },
    // { key: "whiteboardDisplay",                         type: "Boolean",     title: "Whiteboard-Display"              },
    // { key: "discussionGuideTips",                       type: "Boolean",     title: "Session Hosting Tips"            },
    // { key: "secureSsl",                                 type: "Boolean",     title: "Private&Secure (SSL)"            },
    // { key: "canInviteObserversToSession",               type: "Boolean",     title: "Spectators"                      },
  ]
};
