'use strict';
module.exports = {
  features: [
    {key: "accessKlzziForum", title: "Access klzii Forum"},
    {key: "accessKlzziFocus", title: "Access klzii Focus"},
    {key: "sessionCount", title: "Number of Chat Sessions"},
    {key: "contactListCount", title: "Number of Contact Lists"},
    {key: "recruiterContactListCount", title: "Recruiter lists (build Contact Lists on demand)"},
    {key: "exportRecruiterStats", title: "Export Recruiter Stats"},
    {key: "exportRecruiterSurveyData", title: "Export Recruiter Data"},
    {key: "importDatabase", title: "Import&Map Contacts"},
    {key: "exportContactListAndParticipantHistory", title: "Export Contacts"},
    {key: "numberOfContacts", title: "Number of Contacts"},
    {key: "accountUserCount", title: "Number of Managers"},
    {key: "brandLogoAndCustomColors", title: "Custom Logo & Colors"},
    {key: "customEmailInvitationAndReminderMessages", title: "Custom Emails"},
    {key: "planSmsCount", title: "SMS Alerts (Focus)"},
    {key: "topicCount", title: "Number of Topics"},
    {key: "canInviteObserversToSession", title: "Observers"},
    {key: "whiteboardDisplay", title: "Whiteboard-Display"},
    {key: "whiteboardFunctionality", title: "Whiteboard-Interactive"},
    {key: "pinboardDisplay", title: "Pinboard"},
    {key: "uploadToGallery", title: "Multimedia"},
    {key: "voting", title: "Voting"},
    {key: "privateMessaging", title: "Private Messaging"},
    {key: "discussionGuideTips", title: "Facilitator Tips"},
    {key: "reportingFunctions", title: "Export Reporting"},
    {key: "availableOnTabletAndMobilePlatforms", title: "Mobile & Tablet"},
    {key: "secureSsl", title: "Number of Chat Sessions"},
  ],
  free_trial: {
    sessionCount: 1,
    contactListCount: 1,
    recruiterContactListCount: 1,
    importDatabase: true,
    brandLogoAndCustomColors: true,
    contactListMemberCount: -1,
    accountUserCount: 1,
    exportContactListAndParticipantHistory: false,
    exportRecruiterStats: false,
    exportRecruiterSurveyData: false,
    accessKlzziForum: true,
    accessKlzziFocus: true,
    canInviteObserversToSession: true,
    paidSmsCount: 20,
    planSmsCount: 20,
    discussionGuideTips: true,
    whiteboardFunctionality: true,
    whiteboardDisplay: false,
    uploadToGallery: true,
    reportingFunctions: true,
    pinboardDisplay: false,
    voting: false,
    privateMessaging: true,
    availableOnTabletAndMobilePlatforms: true,
    customEmailInvitationAndReminderMessages: true,
    topicCount: -1,
    priority: -1,
    surveyCount: 1,
    secureSsl: true
  },
  free_account: {
    sessionCount: 1,
    contactListCount: 1,
    recruiterContactListCount: 1,
    importDatabase: true,
    brandLogoAndCustomColors: false,
    contactListMemberCount: -1,
    accountUserCount: 1,
    exportContactListAndParticipantHistory: false,
    exportRecruiterStats: true,
    exportRecruiterSurveyData: false,
    accessKlzziForum: true,
    accessKlzziFocus: true,
    canInviteObserversToSession: false,
    paidSmsCount: 0,
    planSmsCount: 0,
    discussionGuideTips: true,
    whiteboardDisplay: true,
    whiteboardFunctionality: false,
    uploadToGallery: false,
    reportingFunctions: false,
    pinboardDisplay: false,
    voting: false,
    privateMessaging: true,
    availableOnTabletAndMobilePlatforms: true,
    customEmailInvitationAndReminderMessages: true,
    topicCount: 5,
    priority: 1,
    surveyCount: 1,
    secureSsl: true
  },
  senior_monthly: {
    sessionCount: 8,
    contactListCount: 4,
    recruiterContactListCount: 4,
    importDatabase: true,
    brandLogoAndCustomColors: true,
    contactListMemberCount: -1,
    accountUserCount: 5,
    exportContactListAndParticipantHistory: true,
    exportRecruiterStats: true,
    exportRecruiterSurveyData: true,
    accessKlzziForum: true,
    accessKlzziFocus: true,
    canInviteObserversToSession: true,
    paidSmsCount: 75,
    planSmsCount: 75,
    discussionGuideTips: true,
    whiteboardDisplay: true,
    whiteboardFunctionality: true,
    uploadToGallery: true,
    reportingFunctions: true,
    pinboardDisplay: true,
    voting: true,
    privateMessaging: true,
    availableOnTabletAndMobilePlatforms: true,
    customEmailInvitationAndReminderMessages: true,
    topicCount: -1,
    priority: 2,
    related: 'senior_yearly',
    surveyCount: 4,
    secureSsl: true
  },
  senior_yearly: {
    sessionCount: 8,
    contactListCount: 4,
    recruiterContactListCount: 4,
    importDatabase: true,
    brandLogoAndCustomColors: true,
    contactListMemberCount: -1,
    accountUserCount: 5,
    exportContactListAndParticipantHistory: true,
    exportRecruiterStats: true,
    exportRecruiterSurveyData: true,
    accessKlzziForum: true,
    accessKlzziFocus: true,
    canInviteObserversToSession: true,
    paidSmsCount: 75,
    planSmsCount: 75,
    discussionGuideTips: true,
    whiteboardDisplay: true,
    whiteboardFunctionality: true,
    uploadToGallery: true,
    reportingFunctions: true,
    pinboardDisplay: true,
    voting: true,
    privateMessaging: true,
    availableOnTabletAndMobilePlatforms: true,
    customEmailInvitationAndReminderMessages: true,
    topicCount: -1,
    priority: 2,
    surveyCount: 4,
    secureSsl: true
  },
  core_monthly: {
    sessionCount: 3,
    contactListCount: 2,
    recruiterContactListCount: 2,
    importDatabase: true,
    brandLogoAndCustomColors: true,
    contactListMemberCount: -1,
    accountUserCount: 2,
    exportContactListAndParticipantHistory: true,
    exportRecruiterStats: true,
    exportRecruiterSurveyData: true,
    accessKlzziForum: true,
    accessKlzziFocus: true,
    canInviteObserversToSession: true,
    paidSmsCount: 50,
    planSmsCount: 50,
    discussionGuideTips: true,
    whiteboardDisplay: true,
    whiteboardFunctionality: true,
    uploadToGallery: true,
    reportingFunctions: true,
    pinboardDisplay: true,
    voting: true,
    privateMessaging: true,
    availableOnTabletAndMobilePlatforms: true,
    customEmailInvitationAndReminderMessages: true,
    topicCount: 20,
    priority: 3,
    related: 'core_yearly',
    surveyCount: 2,
    secureSsl: true
  },
  core_yearly: {
    sessionCount: 3,
    contactListCount: 2,
    recruiterContactListCount: 2,
    importDatabase: true,
    brandLogoAndCustomColors: true,
    contactListMemberCount: -1,
    accountUserCount: 2,
    exportContactListAndParticipantHistory: true,
    exportRecruiterStats: true,
    exportRecruiterSurveyData: true,
    accessKlzziForum: true,
    accessKlzziFocus: true,
    canInviteObserversToSession: true,
    paidSmsCount: 50,
    planSmsCount: 50,
    discussionGuideTips: true,
    whiteboardDisplay: true,
    whiteboardFunctionality: true,
    uploadToGallery: true,
    reportingFunctions: true,
    pinboardDisplay: true,
    voting: true,
    privateMessaging: true,
    availableOnTabletAndMobilePlatforms: true,
    customEmailInvitationAndReminderMessages: true,
    topicCount: 20,
    priority: 3,
    surveyCount: 2,
    secureSsl: true
  },
  junior_monthly: {
    sessionCount: 1,
    contactListCount: 1,
    recruiterContactListCount: 1,
    importDatabase: true,
    brandLogoAndCustomColors: false,
    contactListMemberCount: -1,
    accountUserCount: 1,
    exportContactListAndParticipantHistory: false,
    exportRecruiterStats: true,
    exportRecruiterSurveyData: false,
    accessKlzziForum: true,
    accessKlzziFocus: true,
    canInviteObserversToSession: false,
    paidSmsCount: 20,
    planSmsCount: 20,
    discussionGuideTips: true,
    whiteboardDisplay: true,
    whiteboardFunctionality: false,
    uploadToGallery: true,
    reportingFunctions: true,
    pinboardDisplay: false,
    voting: true,
    privateMessaging: true,
    availableOnTabletAndMobilePlatforms: true,
    customEmailInvitationAndReminderMessages: true,
    topicCount: 5,
    priority: 4,
    related: 'junior_yearly',
    surveyCount: 1,
    secureSsl: true
  },
  junior_yearly: {
    sessionCount: 1,
    contactListCount: 1,
    recruiterContactListCount: 1,
    importDatabase: true,
    brandLogoAndCustomColors: false,
    contactListMemberCount: -1,
    accountUserCount: 1,
    exportContactListAndParticipantHistory: false,
    exportRecruiterStats: true,
    exportRecruiterSurveyData: false,
    accessKlzziForum: true,
    accessKlzziFocus: true,
    canInviteObserversToSession: false,
    paidSmsCount: 20,
    planSmsCount: 20,
    discussionGuideTips: true,
    whiteboardDisplay: true,
    whiteboardFunctionality: false,
    uploadToGallery: true,
    reportingFunctions: true,
    pinboardDisplay: false,
    voting: false,
    privateMessaging: true,
    availableOnTabletAndMobilePlatforms: true,
    customEmailInvitationAndReminderMessages: true,
    topicCount: 5,
    priority: 4,
    surveyCount: 1,
    secureSsl: true
  }
}
