apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: admin
    version: "1"
  name: admin-controller
spec:
  replicas: 3
  selector:
    name: admin
  template:
    metadata:
      labels:
        name: admin
    spec:
      containers:
      - image: "944561038201.dkr.ecr.us-west-2.amazonaws.com/klzii_main:latest"
        name: admin
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: "postgres://klzii:VQqttpXdE42u6PUKWusy@klzii-staging.cyujokxcbe0c.us-west-2.rds.amazonaws.com:5432/klzii_staging"
        - name: SERVER_BASE_DOMAIN
          value: ".admin.codingwithaxe.com"
        - name: SERVER_DOMAIN
          value: "www.admin.codingwithaxe.com"
        - name: SERVER_BASE_SUBDOMAIN
          value: "www"
        - name: SERVER_PORT
          value: "80"
