apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
    env: staging
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: master
    env: staging
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        env: staging
    spec:
      containers:
      - name: redis-redis
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: admin
  labels:
    name: admin
    env: staging
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    name: admin
    env: staging
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: admin
    env: staging
  name: admin
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: admin
        env: staging
        version: "0.0.6"
    spec:
      containers:
      - image: "944561038201.dkr.ecr.us-west-2.amazonaws.com/klzii_main:latest"
        name: admin
        ports:
        - containerPort: 3000
        env:
        - name: REDIS_HOST
          value: "redis-master"
        - name: REDIS_PORT
          value: "6379"
        - name: DATABASE_URL
          value: "postgres://klzii:VQqttpXdE42u6PUKWusy@klzii-staging.cyujokxcbe0c.us-west-2.rds.amazonaws.com:5432/klzii_staging"
        - name: AIRBRAKE_PROJECT_ID
          value: "121542"
        - name: AIRBRAKE_API_KEY
          value: "607e87c9e8b7500497bb84c51162b0a82"
        - name: SERVER_BASE_DOMAIN
          value: ".staging.klzii.com"
        - name: SERVER_DOMAIN
          value: "www.staging.klzii.com"
        - name: SERVER_BASE_SUBDOMAIN
          value: "www"
        - name: SERVER_PORT
          value: "80"
