apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: chat-v1
    version: v1
  name: chat-controller
spec:
  replicas: 1
  selector:
    name: chat
  template:
    metadata:
      labels:
        name: chat
    spec:
      containers:
      - image: 944561038201.dkr.ecr.us-west-2.amazonaws.com/klzii_chat:latest
        name: chat
        ports:
        - containerPort: 3000
        env:
        - name: SECRET_KEY_BASE
          value: 265728C3CEE6D163E3A210D2C7952CF50EF3E1765E3FB69DC13E70C93E6D0EF8
        - name: DB_USERNAME
          value: klzii
        - name: DB_PASSWORD
          value: VQqttpXdE42u6PUKWusy
        - name: DB_HOST
          value: klzii-staging.cyujokxcbe0c.us-west-2.rds.amazonaws.com
        - name: DB_DATABASE
          value: klzii_staging
        - name: SERVER_HOST
          value: chat.codingwithaxe.com
